// database.ts — Re-exporta tipos de core + tipos exclusivos de GymBase
export type {
  UserRole,
  Profile,
  MembershipPlan,
  Subscription,
  SubscriptionStatus,
  PaymentProof,
  PaymentProofWithDetails,
  Content,
  ContentType,
  ContentCategory,
  CommunityPost,
  CommunityComment,
  CommunityReaction,
  ReactionType,
  ActionResult,
  AdminDashboardStats,
  MemberWithSubscription,
} from "@core/types/database";
